source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Pokedex' do
    pod 'SnapKit', '~> 5.0.0'
    pod 'Alamofire', '~> 5.4'
    pod 'Kingfisher', '~> 6.0'
end
